# Generated by Django 2.0.7 on 2018-09-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('textares', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
