# Generated by Django 2.0.7 on 2018-09-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='textares',
            new_name='text',
        ),
    ]
